import { Typography } from '@bambu/react-ui';

export function GoalProjectionDisclaimer() {
  return (
    <Typography color="grey.700" variant="caption" fontWeight={300}>
      <strong>Disclaimer</strong>: The results and/or estimates generated by
      this platform are based on the information provided by you and is intended
      to be used for illustrative purposes only. This platform is not intended
      to provide specific investment objectives, your financial situation, and
      particular needs. No guarantee is made as to its accuracy.
    </Typography>
  );
}

export default GoalProjectionDisclaimer;
