export enum BrokerIntegrationErrorCodesEnum {
  AUTHENTICATION_TOKEN_MISSING = 'AUTHENTICATION_TOKEN_MISSING',
  TENANT_NOT_BOUND_TO_BROKERAGE = 'TENANT_NOT_BOUND_TO_BROKERAGE',
  TENANT_PARTY_NOT_FOUND = 'TENANT_PARTY_NOT_FOUND',
  BROKER_API_RATE_LIMIT_HIT = 'BROKER_API_RATE_LIMIT_HIT',
  BAD_BROKERAGE_REQUEST = 'BAD_BROKERAGE_REQUEST',
  TENANT_PARTY_ADDRESS_NOT_FOUND = 'TENANT_PARTY_ADDRESS_NOT_FOUND',
  IDEMPOTENT_CREATION_REQUEST_ALREADY_SUBMITTED = 'IDEMPOTENT_CREATION_REQUEST_ALREADY_SUBMITTED',
  BANK_ACCOUNT_NOT_FOUND = 'BANK_ACCOUNT_NOT_FOUND',
  BROKERAGE_ACCOUNT_NOT_FOUND = 'BROKERAGE_ACCOUNT_NOT_FOUND',
  BROKERAGE_PORTFOLIO_NOT_FOUND = 'BROKERAGE_PORTFOLIO_NOT_FOUND',
  BROKERAGE_MODEL_PORTFOLIO_NOT_FOUND = 'BROKERAGE_MODEL_PORTFOLIO_NOT_FOUND',
  BROKERAGE_DIRECT_DEBIT_MANDATE_NOT_FOUND = 'BROKERAGE_DIRECT_DEBIT_MANDATE_NOT_FOUND',
}
