export enum StripeIntegrationErrorCodesEnum {
  STRIPE_PRICE_LINE_ITEM_INVALID = 'STRIPE_PRICE_LINE_ITEM_INVALID',
  STRIPE_PRICE_ID_INVALID = 'STRIPE_PRICE_ID_INVALID',
  STRIPE_PRODUCT_ID_INVALID = 'STRIPE_PRODUCT_ID_INVALID',
  STRIPE_SUBSCRIPTION_EXISTS = 'STRIPE_SUBSCRIPTION_EXISTS',
  STRIPE_SUBSCRIPTION_NOT_IN_PLACE = 'STRIPE_SUBSCRIPTION_NOT_IN_PLACE',
  STRIPE_SUBSCRIPTION_NOT_CONNECT = 'STRIPE_SUBSCRIPTION_NOT_CONNECT',
  STRIPE_SUBSCRIPTIONS_NOT_FOUND = 'STRIPE_SUBSCRIPTIONS_NOT_FOUND',
  STRIPE_PRICE_METADATA_INVALID = 'STRIPE_PRICE_METADATA_INVALID',
  STRIPE_PRICE_TYPE_CONNECT_NOT_FOUND = 'STRIPE_PRICE_TYPE_CONNECT_NOT_FOUND',
  STRIPE_PRICE_TYPE_TRANSACT_NOT_FOUND = 'STRIPE_PRICE_TYPE_TRANSACT_NOT_FOUND',
}
