export const COUNTRY_OF_RESIDENCE = [
  {
    code: 'GB',
    internationalDialingCode: '44',
    currencyCode: 'GBP',
    flag: 'https://restcountries.eu/data/gbr.svg',
    cioc: 'GBR',
    name: 'United Kingdom',
    demonym: 'British',
    cca2: 'GB',
    cca3: 'GBR',
    ccn3: '826',
    id: 'GBR',
  },
  {
    code: 'US',
    internationalDialingCode: '1',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/usa.svg',
    cioc: 'USA',
    name: 'United States of America',
    demonym: 'American',
    cca2: 'US',
    cca3: 'USA',
    ccn3: '840',
    id: 'USA',
  },
  {
    code: 'AF',
    internationalDialingCode: '93',
    currencyCode: 'AFN',
    flag: 'https://restcountries.eu/data/afg.svg',
    cioc: 'AFG',
    name: 'Afghanistan',
    demonym: 'Afghan',
    cca2: 'AF',
    cca3: 'AFG',
    ccn3: '004',
    id: 'AFG',
  },
  {
    code: 'AL',
    internationalDialingCode: '355',
    currencyCode: 'ALL',
    flag: 'https://restcountries.eu/data/alb.svg',
    cioc: 'ALB',
    name: 'Albania',
    demonym: 'Albanian',
    cca2: 'AL',
    cca3: 'ALB',
    ccn3: '008',
    id: 'ALB',
  },
  {
    code: 'DZ',
    internationalDialingCode: '213',
    currencyCode: 'DZD',
    flag: 'https://restcountries.eu/data/dza.svg',
    cioc: 'ALG',
    name: 'Algeria',
    demonym: 'Algerian',
    cca2: 'DZ',
    cca3: 'DZA',
    ccn3: '012',
    id: 'DZA',
  },
  {
    code: 'AS',
    internationalDialingCode: '684',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/asm.svg',
    cioc: 'ASA',
    name: 'American Samoa',
    demonym: 'American Samoan',
    cca2: 'AS',
    cca3: 'ASM',
    ccn3: '016',
    id: 'ASM',
  },
  {
    code: 'AD',
    internationalDialingCode: '376',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/and.svg',
    cioc: 'AND',
    name: 'Andorra',
    demonym: 'Andorran',
    cca2: 'AD',
    cca3: 'AND',
    ccn3: '020',
    id: 'AND',
  },
  {
    code: 'AO',
    internationalDialingCode: '244',
    currencyCode: 'AOA',
    flag: 'https://restcountries.eu/data/ago.svg',
    cioc: 'ANG',
    name: 'Angola',
    demonym: 'Angolan',
    cca2: 'AO',
    cca3: 'AGO',
    ccn3: '024',
    id: 'AGO',
  },
  {
    code: 'AI',
    internationalDialingCode: '264',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/aia.svg',
    cioc: 'AIA',
    name: 'Anguilla',
    demonym: 'Anguillian',
    cca2: 'AI',
    cca3: 'AIA',
    ccn3: '660',
    id: 'AIA',
  },
  {
    code: 'AQ',
    internationalDialingCode: '672',
    currencyCode: 'AUD',
    flag: 'https://restcountries.eu/data/ata.svg',
    cioc: 'ATA',
    name: 'Antarctica',
    demonym: 'Antarctica',
    cca2: 'AQ',
    cca3: 'ATA',
    ccn3: '010',
    id: 'ATA',
  },
  {
    code: 'AG',
    internationalDialingCode: '268',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/atg.svg',
    cioc: 'ANT',
    name: 'Antigua and Barbuda',
    demonym: 'Antiguan, Barbudan',
    cca2: 'AG',
    cca3: 'ATG',
    ccn3: '028',
    id: 'ATG',
  },
  {
    code: 'AR',
    internationalDialingCode: '54',
    currencyCode: 'ARS',
    flag: 'https://restcountries.eu/data/arg.svg',
    cioc: 'ARG',
    name: 'Argentina',
    demonym: 'Argentinean',
    cca2: 'AR',
    cca3: 'ARG',
    ccn3: '032',
    id: 'ARG',
  },
  {
    code: 'AM',
    internationalDialingCode: '374',
    currencyCode: 'AMD',
    flag: 'https://restcountries.eu/data/arm.svg',
    cioc: 'ARM',
    name: 'Armenia',
    demonym: 'Armenian',
    cca2: 'AM',
    cca3: 'ARM',
    ccn3: '051',
    id: 'ARM',
  },
  {
    code: 'AW',
    internationalDialingCode: '297',
    currencyCode: 'AWG',
    flag: 'https://restcountries.eu/data/abw.svg',
    cioc: 'ARU',
    name: 'Aruba',
    demonym: 'Aruban',
    cca2: 'AW',
    cca3: 'ABW',
    ccn3: '533',
    id: 'ABW',
  },
  {
    code: 'AU',
    internationalDialingCode: '61',
    currencyCode: 'AUD',
    flag: 'https://restcountries.eu/data/aus.svg',
    cioc: 'AUS',
    name: 'Australia',
    demonym: 'Australian',
    cca2: 'AU',
    cca3: 'AUS',
    ccn3: '036',
    id: 'AUS',
  },
  {
    code: 'AT',
    internationalDialingCode: '43',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/aut.svg',
    cioc: 'AUT',
    name: 'Austria',
    demonym: 'Austrian',
    cca2: 'AT',
    cca3: 'AUT',
    ccn3: '040',
    id: 'AUT',
  },
  {
    code: 'AZ',
    internationalDialingCode: '994',
    currencyCode: 'AZN',
    flag: 'https://restcountries.eu/data/aze.svg',
    cioc: 'AZE',
    name: 'Azerbaijan',
    demonym: 'Azerbaijani',
    cca2: 'AZ',
    cca3: 'AZE',
    ccn3: '031',
    id: 'AZE',
  },
  {
    code: 'BS',
    internationalDialingCode: '242',
    currencyCode: 'BSD',
    flag: 'https://restcountries.eu/data/bhs.svg',
    cioc: 'BAH',
    name: 'Bahamas',
    demonym: 'Bahamian',
    cca2: 'BS',
    cca3: 'BHS',
    ccn3: '044',
    id: 'BHS',
  },
  {
    code: 'BH',
    internationalDialingCode: '973',
    currencyCode: 'BHD',
    flag: 'https://restcountries.eu/data/bhr.svg',
    cioc: 'BRN',
    name: 'Bahrain',
    demonym: 'Bahraini',
    cca2: 'BH',
    cca3: 'BHR',
    ccn3: '048',
    id: 'BHR',
  },
  {
    code: 'BD',
    internationalDialingCode: '880',
    currencyCode: 'BDT',
    flag: 'https://restcountries.eu/data/bgd.svg',
    cioc: 'BAN',
    name: 'Bangladesh',
    demonym: 'Bangladeshi',
    cca2: 'BD',
    cca3: 'BGD',
    ccn3: '050',
    id: 'BGD',
  },
  {
    code: 'BB',
    internationalDialingCode: '246',
    currencyCode: 'BBD',
    flag: 'https://restcountries.eu/data/brb.svg',
    cioc: 'BAR',
    name: 'Barbados',
    demonym: 'Barbadian',
    cca2: 'BB',
    cca3: 'BRB',
    ccn3: '052',
    id: 'BRB',
  },
  {
    code: 'BY',
    internationalDialingCode: '375',
    currencyCode: 'BYN',
    flag: 'https://restcountries.eu/data/blr.svg',
    cioc: 'BLR',
    name: 'Belarus',
    demonym: 'Belarusian',
    cca2: 'BY',
    cca3: 'BLR',
    ccn3: '112',
    id: 'BLR',
  },
  {
    code: 'BE',
    internationalDialingCode: '32',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/bel.svg',
    cioc: 'BEL',
    name: 'Belgium',
    demonym: 'Belgian',
    cca2: 'BE',
    cca3: 'BEL',
    ccn3: '056',
    id: 'BEL',
  },
  {
    code: 'BZ',
    internationalDialingCode: '501',
    currencyCode: 'BZD',
    flag: 'https://restcountries.eu/data/blz.svg',
    cioc: 'BIZ',
    name: 'Belize',
    demonym: 'Belizean',
    cca2: 'BZ',
    cca3: 'BLZ',
    ccn3: '084',
    id: 'BLZ',
  },
  {
    code: 'BJ',
    internationalDialingCode: '229',
    currencyCode: 'XOF',
    flag: 'https://restcountries.eu/data/ben.svg',
    cioc: 'BEN',
    name: 'Benin',
    demonym: 'Beninese',
    cca2: 'BJ',
    cca3: 'BEN',
    ccn3: '204',
    id: 'BEN',
  },
  {
    code: 'BM',
    internationalDialingCode: '441',
    currencyCode: 'BMD',
    flag: 'https://restcountries.eu/data/bmu.svg',
    cioc: 'BER',
    name: 'Bermuda',
    demonym: 'Bermudian',
    cca2: 'BM',
    cca3: 'BMU',
    ccn3: '060',
    id: 'BMU',
  },
  {
    code: 'BT',
    internationalDialingCode: '975',
    currencyCode: 'BTN',
    flag: 'https://restcountries.eu/data/btn.svg',
    cioc: 'BHU',
    name: 'Bhutan',
    demonym: 'Bhutanese',
    cca2: 'BT',
    cca3: 'BTN',
    ccn3: '064',
    id: 'BTN',
  },
  {
    code: 'BO',
    internationalDialingCode: '591',
    currencyCode: 'BOB',
    flag: 'https://restcountries.eu/data/bol.svg',
    cioc: 'BOL',
    name: 'Bolivia',
    demonym: 'Bolivian',
    cca2: 'BO',
    cca3: 'BOL',
    ccn3: '068',
    id: 'BOL',
  },
  {
    code: 'BA',
    internationalDialingCode: '387',
    currencyCode: 'BAM',
    flag: 'https://restcountries.eu/data/bih.svg',
    cioc: 'BIH',
    name: 'Bosnia and Herzegovina',
    demonym: 'Bosnian',
    cca2: 'BA',
    cca3: 'BIH',
    ccn3: '070',
    id: 'BIH',
  },
  {
    code: 'BW',
    internationalDialingCode: '267',
    currencyCode: 'BWP',
    flag: 'https://restcountries.eu/data/bwa.svg',
    cioc: 'BOT',
    name: 'Botswana',
    demonym: 'Motswana',
    cca2: 'BW',
    cca3: 'BWA',
    ccn3: '072',
    id: 'BWA',
  },
  {
    code: 'BR',
    internationalDialingCode: '55',
    currencyCode: 'BRL',
    flag: 'https://restcountries.eu/data/bra.svg',
    cioc: 'BRA',
    name: 'Brazil',
    demonym: 'Brazilian',
    cca2: 'BR',
    cca3: 'BRA',
    ccn3: '076',
    id: 'BRA',
  },
  {
    code: 'IO',
    internationalDialingCode: '246',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/iot.svg',
    cioc: 'IOT',
    name: 'British Indian Ocean Territory',
    demonym: 'Indian',
    cca2: 'IO',
    cca3: 'IOT',
    ccn3: '086',
    id: 'IOT',
  },
  {
    code: 'BN',
    internationalDialingCode: '673',
    currencyCode: 'BND',
    flag: 'https://restcountries.eu/data/brn.svg',
    cioc: 'BRU',
    name: 'Brunei Darussalam',
    demonym: 'Bruneian',
    cca2: 'BN',
    cca3: 'BRN',
    ccn3: '096',
    id: 'BRN',
  },
  {
    code: 'BG',
    internationalDialingCode: '359',
    currencyCode: 'BGN',
    flag: 'https://restcountries.eu/data/bgr.svg',
    cioc: 'BUL',
    name: 'Bulgaria',
    demonym: 'Bulgarian',
    cca2: 'BG',
    cca3: 'BGR',
    ccn3: '100',
    id: 'BGR',
  },
  {
    code: 'BF',
    internationalDialingCode: '226',
    currencyCode: 'XOF',
    flag: 'https://restcountries.eu/data/bfa.svg',
    cioc: 'BUR',
    name: 'Burkina Faso',
    demonym: 'Burkinabe',
    cca2: 'BF',
    cca3: 'BFA',
    ccn3: '854',
    id: 'BFA',
  },
  {
    code: 'BI',
    internationalDialingCode: '257',
    currencyCode: 'BIF',
    flag: 'https://restcountries.eu/data/bdi.svg',
    cioc: 'BDI',
    name: 'Burundi',
    demonym: 'Burundian',
    cca2: 'BI',
    cca3: 'BDI',
    ccn3: '108',
    id: 'BDI',
  },
  {
    code: 'CV',
    internationalDialingCode: '238',
    currencyCode: 'CVE',
    flag: 'https://restcountries.eu/data/cpv.svg',
    cioc: 'CPV',
    name: 'Cabo Verde',
    demonym: 'Cape Verdian',
    cca2: 'CV',
    cca3: 'CPV',
    ccn3: '132',
    id: 'CPV',
  },
  {
    code: 'KH',
    internationalDialingCode: '855',
    currencyCode: 'KHR',
    flag: 'https://restcountries.eu/data/khm.svg',
    cioc: 'CAM',
    name: 'Cambodia',
    demonym: 'Cambodian',
    cca2: 'KH',
    cca3: 'KHM',
    ccn3: '116',
    id: 'KHM',
  },
  {
    code: 'CM',
    internationalDialingCode: '237',
    currencyCode: 'XAF',
    flag: 'https://restcountries.eu/data/cmr.svg',
    cioc: 'CMR',
    name: 'Cameroon',
    demonym: 'Cameroonian',
    cca2: 'CM',
    cca3: 'CMR',
    ccn3: '120',
    id: 'CMR',
  },
  {
    code: 'CA',
    internationalDialingCode: '1',
    currencyCode: 'CAD',
    flag: 'https://restcountries.eu/data/can.svg',
    cioc: 'CAN',
    name: 'Canada',
    demonym: 'Canadian',
    cca2: 'CA',
    cca3: 'CAN',
    ccn3: '124',
    id: 'CAN',
  },
  {
    code: 'KY',
    internationalDialingCode: '345',
    currencyCode: 'KYD',
    flag: 'https://restcountries.eu/data/cym.svg',
    cioc: 'CAY',
    name: 'Cayman Islands',
    demonym: 'Caymanian',
    cca2: 'KY',
    cca3: 'CYM',
    ccn3: '136',
    id: 'CYM',
  },
  {
    code: 'CF',
    internationalDialingCode: '236',
    currencyCode: 'XAF',
    flag: 'https://restcountries.eu/data/caf.svg',
    cioc: 'CAF',
    name: 'Central African Republic',
    demonym: 'Central African',
    cca2: 'CF',
    cca3: 'CAF',
    ccn3: '140',
    id: 'CAF',
  },
  {
    code: 'TD',
    internationalDialingCode: '235',
    currencyCode: 'XAF',
    flag: 'https://restcountries.eu/data/tcd.svg',
    cioc: 'CHA',
    name: 'Chad',
    demonym: 'Chadian',
    cca2: 'TD',
    cca3: 'TCD',
    ccn3: '148',
    id: 'TCD',
  },
  {
    code: 'CL',
    internationalDialingCode: '56',
    currencyCode: 'CLP',
    flag: 'https://restcountries.eu/data/chl.svg',
    cioc: 'CHI',
    name: 'Chile',
    demonym: 'Chilean',
    cca2: 'CL',
    cca3: 'CHL',
    ccn3: '152',
    id: 'CHL',
  },
  {
    code: 'CN',
    internationalDialingCode: '86',
    currencyCode: 'CNY',
    flag: 'https://restcountries.eu/data/chn.svg',
    cioc: 'CHN',
    name: 'China',
    demonym: 'Chinese',
    cca2: 'CN',
    cca3: 'CHN',
    ccn3: '156',
    id: 'CHN',
  },
  {
    code: 'CX',
    internationalDialingCode: '61',
    currencyCode: 'AUD',
    flag: 'https://restcountries.eu/data/cxr.svg',
    cioc: 'CXR',
    name: 'Christmas Island',
    demonym: 'Christmas Island',
    cca2: 'CX',
    cca3: 'CXR',
    ccn3: '162',
    id: 'CXR',
  },
  {
    code: 'CC',
    internationalDialingCode: '61',
    currencyCode: 'AUD',
    flag: 'https://restcountries.eu/data/cck.svg',
    cioc: 'CCK',
    name: 'Cocos (Keeling) Islands',
    demonym: 'Cocos Islander',
    cca2: 'CC',
    cca3: 'CCK',
    ccn3: '166',
    id: 'CCK',
  },
  {
    code: 'CO',
    internationalDialingCode: '57',
    currencyCode: 'COP',
    flag: 'https://restcountries.eu/data/col.svg',
    cioc: 'COL',
    name: 'Colombia',
    demonym: 'Colombian',
    cca2: 'CO',
    cca3: 'COL',
    ccn3: '170',
    id: 'COL',
  },
  {
    code: 'KM',
    internationalDialingCode: '269',
    currencyCode: 'KMF',
    flag: 'https://restcountries.eu/data/com.svg',
    cioc: 'COM',
    name: 'Comoros',
    demonym: 'Comoran',
    cca2: 'KM',
    cca3: 'COM',
    ccn3: '174',
    id: 'COM',
  },
  {
    code: 'CD',
    internationalDialingCode: '243',
    currencyCode: 'CDF',
    flag: 'https://restcountries.eu/data/cod.svg',
    cioc: 'COD',
    name: 'Congo',
    demonym: 'Congolese',
    cca2: 'CD',
    cca3: 'COD',
    ccn3: '180',
    id: 'COD',
  },
  {
    code: 'CG',
    internationalDialingCode: '242',
    currencyCode: 'XAF',
    flag: 'https://restcountries.eu/data/cog.svg',
    cioc: 'CGO',
    name: 'Congo',
    demonym: 'Congolese',
    cca2: 'CG',
    cca3: 'COG',
    ccn3: '178',
    id: 'COG',
  },
  {
    code: 'CK',
    internationalDialingCode: '682',
    currencyCode: 'NZD',
    flag: 'https://restcountries.eu/data/cok.svg',
    cioc: 'COK',
    name: 'Cook Islands',
    demonym: 'Cook Islander',
    cca2: 'CK',
    cca3: 'COK',
    ccn3: '184',
    id: 'COK',
  },
  {
    code: 'CR',
    internationalDialingCode: '506',
    currencyCode: 'CRC',
    flag: 'https://restcountries.eu/data/cri.svg',
    cioc: 'CRC',
    name: 'Costa Rica',
    demonym: 'Costa Rican',
    cca2: 'CR',
    cca3: 'CRI',
    ccn3: '188',
    id: 'CRI',
  },
  {
    code: 'HR',
    internationalDialingCode: '385',
    currencyCode: 'HRK',
    flag: 'https://restcountries.eu/data/hrv.svg',
    cioc: 'CRO',
    name: 'Croatia',
    demonym: 'Croatian',
    cca2: 'HR',
    cca3: 'HRV',
    ccn3: '191',
    id: 'HRV',
  },
  {
    code: 'CU',
    internationalDialingCode: '53',
    currencyCode: 'CUC',
    flag: 'https://restcountries.eu/data/cub.svg',
    cioc: 'CUB',
    name: 'Cuba',
    demonym: 'Cuban',
    cca2: 'CU',
    cca3: 'CUB',
    ccn3: '192',
    id: 'CUB',
  },
  {
    code: 'CW',
    internationalDialingCode: '599',
    currencyCode: 'ANG',
    flag: 'https://restcountries.eu/data/cuw.svg',
    cioc: 'CUW',
    name: 'Curacao',
    demonym: 'Dutch',
    cca2: 'CW',
    cca3: 'CUW',
    ccn3: '531',
    id: 'CUW',
  },
  {
    code: 'CY',
    internationalDialingCode: '357',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/cyp.svg',
    cioc: 'CYP',
    name: 'Cyprus',
    demonym: 'Cypriot',
    cca2: 'CY',
    cca3: 'CYP',
    ccn3: '196',
    id: 'CYP',
  },
  {
    code: 'CZ',
    internationalDialingCode: '420',
    currencyCode: 'CZK',
    flag: 'https://restcountries.eu/data/cze.svg',
    cioc: 'CZE',
    name: 'Czech Republic',
    demonym: 'Czech',
    cca2: 'CZ',
    cca3: 'CZE',
    ccn3: '203',
    id: 'CZE',
  },
  {
    code: 'DK',
    internationalDialingCode: '45',
    currencyCode: 'DKK',
    flag: 'https://restcountries.eu/data/dnk.svg',
    cioc: 'DEN',
    name: 'Denmark',
    demonym: 'Danish',
    cca2: 'DK',
    cca3: 'DNK',
    ccn3: '208',
    id: 'DNK',
  },
  {
    code: 'DJ',
    internationalDialingCode: '253',
    currencyCode: 'DJF',
    flag: 'https://restcountries.eu/data/dji.svg',
    cioc: 'DJI',
    name: 'Djibouti',
    demonym: 'Djibouti',
    cca2: 'DJ',
    cca3: 'DJI',
    ccn3: '262',
    id: 'DJI',
  },
  {
    code: 'DM',
    internationalDialingCode: '767',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/dma.svg',
    cioc: 'DMA',
    name: 'Dominica',
    demonym: 'Dominican',
    cca2: 'DM',
    cca3: 'DMA',
    ccn3: '212',
    id: 'DMA',
  },
  {
    code: 'EC',
    internationalDialingCode: '593',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/ecu.svg',
    cioc: 'ECU',
    name: 'Ecuador',
    demonym: 'Ecuadorean',
    cca2: 'EC',
    cca3: 'ECU',
    ccn3: '218',
    id: 'ECU',
  },
  {
    code: 'EG',
    internationalDialingCode: '20',
    currencyCode: 'EGP',
    flag: 'https://restcountries.eu/data/egy.svg',
    cioc: 'EGY',
    name: 'Egypt',
    demonym: 'Egyptian',
    cca2: 'EG',
    cca3: 'EGY',
    ccn3: '818',
    id: 'EGY',
  },
  {
    code: 'SV',
    internationalDialingCode: '503',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/slv.svg',
    cioc: 'ESA',
    name: 'El Salvador',
    demonym: 'Salvadoran',
    cca2: 'SV',
    cca3: 'SLV',
    ccn3: '222',
    id: 'SLV',
  },
  {
    code: 'GQ',
    internationalDialingCode: '240',
    currencyCode: 'XAF',
    flag: 'https://restcountries.eu/data/gnq.svg',
    cioc: 'GEQ',
    name: 'Equatorial Guinea',
    demonym: 'Equatorial Guinean',
    cca2: 'GQ',
    cca3: 'GNQ',
    ccn3: '226',
    id: 'GNQ',
  },
  {
    code: 'ER',
    internationalDialingCode: '291',
    currencyCode: 'ERN',
    flag: 'https://restcountries.eu/data/eri.svg',
    cioc: 'ERI',
    name: 'Eritrea',
    demonym: 'Eritrean',
    cca2: 'ER',
    cca3: 'ERI',
    ccn3: '232',
    id: 'ERI',
  },
  {
    code: 'EE',
    internationalDialingCode: '372',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/est.svg',
    cioc: 'EST',
    name: 'Estonia',
    demonym: 'Estonian',
    cca2: 'EE',
    cca3: 'EST',
    ccn3: '233',
    id: 'EST',
  },
  {
    code: 'ET',
    internationalDialingCode: '251',
    currencyCode: 'ETB',
    flag: 'https://restcountries.eu/data/eth.svg',
    cioc: 'ETH',
    name: 'Ethiopia',
    demonym: 'Ethiopian',
    cca2: 'ET',
    cca3: 'ETH',
    ccn3: '231',
    id: 'ETH',
  },
  {
    code: 'FK',
    internationalDialingCode: '500',
    currencyCode: 'FKP',
    flag: 'https://restcountries.eu/data/flk.svg',
    cioc: 'FLK',
    name: 'Falkland Islands',
    demonym: 'Falkland Islander',
    cca2: 'FK',
    cca3: 'FLK',
    ccn3: '238',
    id: 'FLK',
  },
  {
    code: 'FO',
    internationalDialingCode: '298',
    currencyCode: 'DKK',
    flag: 'https://restcountries.eu/data/fro.svg',
    cioc: 'FRO',
    name: 'Faroe Islands',
    demonym: 'Faroese',
    cca2: 'FO',
    cca3: 'FRO',
    ccn3: '234',
    id: 'FRO',
  },
  {
    code: 'FJ',
    internationalDialingCode: '679',
    currencyCode: 'FJD',
    flag: 'https://restcountries.eu/data/fji.svg',
    cioc: 'FIJ',
    name: 'Fiji',
    demonym: 'Fijian',
    cca2: 'FJ',
    cca3: 'FJI',
    ccn3: '242',
    id: 'FJI',
  },
  {
    code: 'FI',
    internationalDialingCode: '358',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/fin.svg',
    cioc: 'FIN',
    name: 'Finland',
    demonym: 'Finnish',
    cca2: 'FI',
    cca3: 'FIN',
    ccn3: '246',
    id: 'FIN',
  },
  {
    code: 'FR',
    internationalDialingCode: '33',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/fra.svg',
    cioc: 'FRA',
    name: 'France',
    demonym: 'French',
    cca2: 'FR',
    cca3: 'FRA',
    ccn3: '250',
    id: 'FRA',
  },
  {
    code: 'PF',
    internationalDialingCode: '689',
    currencyCode: 'XPF',
    flag: 'https://restcountries.eu/data/pyf.svg',
    cioc: 'PYF',
    name: 'French Polynesia',
    demonym: 'French Polynesian',
    cca2: 'PF',
    cca3: 'PYF',
    ccn3: '258',
    id: 'PYF',
  },
  {
    code: 'GA',
    internationalDialingCode: '241',
    currencyCode: 'XAF',
    flag: 'https://restcountries.eu/data/gab.svg',
    cioc: 'GAB',
    name: 'Gabon',
    demonym: 'Gabonese',
    cca2: 'GA',
    cca3: 'GAB',
    ccn3: '266',
    id: 'GAB',
  },
  {
    code: 'GM',
    internationalDialingCode: '220',
    currencyCode: 'GMD',
    flag: 'https://restcountries.eu/data/gmb.svg',
    cioc: 'GAM',
    name: 'Gambia',
    demonym: 'Gambian',
    cca2: 'GM',
    cca3: 'GMB',
    ccn3: '270',
    id: 'GMB',
  },
  {
    code: 'GE',
    internationalDialingCode: '995',
    currencyCode: 'GEL',
    flag: 'https://restcountries.eu/data/geo.svg',
    cioc: 'GEO',
    name: 'Georgia',
    demonym: 'Georgian',
    cca2: 'GE',
    cca3: 'GEO',
    ccn3: '268',
    id: 'GEO',
  },
  {
    code: 'DE',
    internationalDialingCode: '49',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/deu.svg',
    cioc: 'GER',
    name: 'Germany',
    demonym: 'German',
    cca2: 'DE',
    cca3: 'DEU',
    ccn3: '276',
    id: 'DEU',
  },
  {
    code: 'GH',
    internationalDialingCode: '233',
    currencyCode: 'GHS',
    flag: 'https://restcountries.eu/data/gha.svg',
    cioc: 'GHA',
    name: 'Ghana',
    demonym: 'Ghanaian',
    cca2: 'GH',
    cca3: 'GHA',
    ccn3: '288',
    id: 'GHA',
  },
  {
    code: 'GI',
    internationalDialingCode: '350',
    currencyCode: 'GIP',
    flag: 'https://restcountries.eu/data/gib.svg',
    cioc: 'GIB',
    name: 'Gibraltar',
    demonym: 'Gibraltar',
    cca2: 'GI',
    cca3: 'GIB',
    ccn3: '292',
    id: 'GIB',
  },
  {
    code: 'GR',
    internationalDialingCode: '30',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/grc.svg',
    cioc: 'GRE',
    name: 'Greece',
    demonym: 'Greek',
    cca2: 'GR',
    cca3: 'GRC',
    ccn3: '300',
    id: 'GRC',
  },
  {
    code: 'GL',
    internationalDialingCode: '299',
    currencyCode: 'DKK',
    flag: 'https://restcountries.eu/data/grl.svg',
    cioc: 'GRL',
    name: 'Greenland',
    demonym: 'Greenlandic',
    cca2: 'GL',
    cca3: 'GRL',
    ccn3: '304',
    id: 'GRL',
  },
  {
    code: 'GD',
    internationalDialingCode: '473',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/grd.svg',
    cioc: 'GRN',
    name: 'Grenada',
    demonym: 'Grenadian',
    cca2: 'GD',
    cca3: 'GRD',
    ccn3: '308',
    id: 'GRD',
  },
  {
    code: 'GU',
    internationalDialingCode: '671',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/gum.svg',
    cioc: 'GUM',
    name: 'Guam',
    demonym: 'Guamanian',
    cca2: 'GU',
    cca3: 'GUM',
    ccn3: '316',
    id: 'GUM',
  },
  {
    code: 'GT',
    internationalDialingCode: '502',
    currencyCode: 'GTQ',
    flag: 'https://restcountries.eu/data/gtm.svg',
    cioc: 'GUA',
    name: 'Guatemala',
    demonym: 'Guatemalan',
    cca2: 'GT',
    cca3: 'GTM',
    ccn3: '320',
    id: 'GTM',
  },
  {
    code: 'GN',
    internationalDialingCode: '224',
    currencyCode: 'GNF',
    flag: 'https://restcountries.eu/data/gin.svg',
    cioc: 'GUI',
    name: 'Guinea',
    demonym: 'Guinean',
    cca2: 'GN',
    cca3: 'GIN',
    ccn3: '324',
    id: 'GIN',
  },
  {
    code: 'GW',
    internationalDialingCode: '245',
    currencyCode: 'XOF',
    flag: 'https://restcountries.eu/data/gnb.svg',
    cioc: 'GBS',
    name: 'Guinea-Bissau',
    demonym: 'Guinea-Bissauan',
    cca2: 'GW',
    cca3: 'GNB',
    ccn3: '624',
    id: 'GNB',
  },
  {
    code: 'GY',
    internationalDialingCode: '592',
    currencyCode: 'GYD',
    flag: 'https://restcountries.eu/data/guy.svg',
    cioc: 'GUY',
    name: 'Guyana',
    demonym: 'Guyanese',
    cca2: 'GY',
    cca3: 'GUY',
    ccn3: '328',
    id: 'GUY',
  },
  {
    code: 'HT',
    internationalDialingCode: '509',
    currencyCode: 'HTG',
    flag: 'https://restcountries.eu/data/hti.svg',
    cioc: 'HAI',
    name: 'Haiti',
    demonym: 'Haitian',
    cca2: 'HT',
    cca3: 'HTI',
    ccn3: '332',
    id: 'HTI',
  },
  {
    code: 'VA',
    internationalDialingCode: '379',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/vat.svg',
    cioc: 'VAT',
    name: 'Holy See',
    demonym: 'Holy See',
    cca2: 'VA',
    cca3: 'VAT',
    ccn3: '336',
    id: 'VAT',
  },
  {
    code: 'HN',
    internationalDialingCode: '504',
    currencyCode: 'HNL',
    flag: 'https://restcountries.eu/data/hnd.svg',
    cioc: 'HON',
    name: 'Honduras',
    demonym: 'Honduran',
    cca2: 'HN',
    cca3: 'HND',
    ccn3: '340',
    id: 'HND',
  },
  {
    code: 'HK',
    internationalDialingCode: '852',
    currencyCode: 'HKD',
    flag: 'https://restcountries.eu/data/hkg.svg',
    cioc: 'HKG',
    name: 'Hong Kong',
    demonym: 'Chinese',
    cca2: 'HK',
    cca3: 'HKG',
    ccn3: '344',
    id: 'HKG',
  },
  {
    code: 'HU',
    internationalDialingCode: '36',
    currencyCode: 'HUF',
    flag: 'https://restcountries.eu/data/hun.svg',
    cioc: 'HUN',
    name: 'Hungary',
    demonym: 'Hungarian',
    cca2: 'HU',
    cca3: 'HUN',
    ccn3: '348',
    id: 'HUN',
  },
  {
    code: 'IS',
    internationalDialingCode: '354',
    currencyCode: 'ISK',
    flag: 'https://restcountries.eu/data/isl.svg',
    cioc: 'ISL',
    name: 'Iceland',
    demonym: 'Icelander',
    cca2: 'IS',
    cca3: 'ISL',
    ccn3: '352',
    id: 'ISL',
  },
  {
    code: 'IN',
    internationalDialingCode: '91',
    currencyCode: 'INR',
    flag: 'https://restcountries.eu/data/ind.svg',
    cioc: 'IND',
    name: 'India',
    demonym: 'Indian',
    cca2: 'IN',
    cca3: 'IND',
    ccn3: '356',
    id: 'IND',
  },
  {
    code: 'ID',
    internationalDialingCode: '62',
    currencyCode: 'IDR',
    flag: 'https://restcountries.eu/data/idn.svg',
    cioc: 'INA',
    name: 'Indonesia',
    demonym: 'Indonesian',
    cca2: 'ID',
    cca3: 'IDN',
    ccn3: '360',
    id: 'IDN',
  },
  {
    code: 'IR',
    internationalDialingCode: '98',
    currencyCode: 'IRR',
    flag: 'https://restcountries.eu/data/irn.svg',
    cioc: 'IRI',
    name: 'Iran',
    demonym: 'Iranian',
    cca2: 'IR',
    cca3: 'IRN',
    ccn3: '364',
    id: 'IRN',
  },
  {
    code: 'IQ',
    internationalDialingCode: '964',
    currencyCode: 'IQD',
    flag: 'https://restcountries.eu/data/irq.svg',
    cioc: 'IRQ',
    name: 'Iraq',
    demonym: 'Iraqi',
    cca2: 'IQ',
    cca3: 'IRQ',
    ccn3: '368',
    id: 'IRQ',
  },
  {
    code: 'IE',
    internationalDialingCode: '353',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/irl.svg',
    cioc: 'IRL',
    name: 'Ireland',
    demonym: 'Irish',
    cca2: 'IE',
    cca3: 'IRL',
    ccn3: '372',
    id: 'IRL',
  },
  {
    code: 'IL',
    internationalDialingCode: '972',
    currencyCode: 'ILS',
    flag: 'https://restcountries.eu/data/isr.svg',
    cioc: 'ISR',
    name: 'Israel',
    demonym: 'Israeli',
    cca2: 'IL',
    cca3: 'ISR',
    ccn3: '376',
    id: 'ISR',
  },
  {
    code: 'IT',
    internationalDialingCode: '39',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/ita.svg',
    cioc: 'ITA',
    name: 'Italy',
    demonym: 'Italian',
    cca2: 'IT',
    cca3: 'ITA',
    ccn3: '380',
    id: 'ITA',
  },
  {
    code: 'JM',
    internationalDialingCode: '876',
    currencyCode: 'JMD',
    flag: 'https://restcountries.eu/data/jam.svg',
    cioc: 'JAM',
    name: 'Jamaica',
    demonym: 'Jamaican',
    cca2: 'JM',
    cca3: 'JAM',
    ccn3: '388',
    id: 'JAM',
  },
  {
    code: 'JP',
    internationalDialingCode: '81',
    currencyCode: 'JPY',
    flag: 'https://restcountries.eu/data/jpn.svg',
    cioc: 'JPN',
    name: 'Japan',
    demonym: 'Japanese',
    cca2: 'JP',
    cca3: 'JPN',
    ccn3: '392',
    id: 'JPN',
  },
  {
    code: 'JO',
    internationalDialingCode: '962',
    currencyCode: 'JOD',
    flag: 'https://restcountries.eu/data/jor.svg',
    cioc: 'JOR',
    name: 'Jordan',
    demonym: 'Jordanian',
    cca2: 'JO',
    cca3: 'JOR',
    ccn3: '400',
    id: 'JOR',
  },
  {
    code: 'KZ',
    internationalDialingCode: '7',
    currencyCode: 'KZT',
    flag: 'https://restcountries.eu/data/kaz.svg',
    cioc: 'KAZ',
    name: 'Kazakhstan',
    demonym: 'Kazakhstani',
    cca2: 'KZ',
    cca3: 'KAZ',
    ccn3: '398',
    id: 'KAZ',
  },
  {
    code: 'KE',
    internationalDialingCode: '254',
    currencyCode: 'KES',
    flag: 'https://restcountries.eu/data/ken.svg',
    cioc: 'KEN',
    name: 'Kenya',
    demonym: 'Kenyan',
    cca2: 'KE',
    cca3: 'KEN',
    ccn3: '404',
    id: 'KEN',
  },
  {
    code: 'KI',
    internationalDialingCode: '686',
    currencyCode: 'AUD',
    flag: 'https://restcountries.eu/data/kir.svg',
    cioc: 'KIR',
    name: 'Kiribati',
    demonym: 'I-Kiribati',
    cca2: 'KI',
    cca3: 'KIR',
    ccn3: '296',
    id: 'KIR',
  },
  {
    code: 'KR',
    internationalDialingCode: '82',
    currencyCode: 'KRW',
    flag: 'https://restcountries.eu/data/kor.svg',
    cioc: 'KOR',
    name: 'Korea (Republic of)',
    demonym: 'South Korean',
    cca2: 'KR',
    cca3: 'KOR',
    ccn3: '410',
    id: 'KOR',
  },
  {
    code: 'KW',
    internationalDialingCode: '965',
    currencyCode: 'KWD',
    flag: 'https://restcountries.eu/data/kwt.svg',
    cioc: 'KUW',
    name: 'Kuwait',
    demonym: 'Kuwaiti',
    cca2: 'KW',
    cca3: 'KWT',
    ccn3: '414',
    id: 'KWT',
  },
  {
    code: 'KG',
    internationalDialingCode: '996',
    currencyCode: 'KGS',
    flag: 'https://restcountries.eu/data/kgz.svg',
    cioc: 'KGZ',
    name: 'Kyrgyzstan',
    demonym: 'Kirghiz',
    cca2: 'KG',
    cca3: 'KGZ',
    ccn3: '417',
    id: 'KGZ',
  },
  {
    code: 'LA',
    internationalDialingCode: '856',
    currencyCode: 'LAK',
    flag: 'https://restcountries.eu/data/lao.svg',
    cioc: 'LAO',
    name: 'Lao',
    demonym: 'Laotian',
    cca2: 'LA',
    cca3: 'LAO',
    ccn3: '418',
    id: 'LAO',
  },
  {
    code: 'LV',
    internationalDialingCode: '371',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/lva.svg',
    cioc: 'LAT',
    name: 'Latvia',
    demonym: 'Latvian',
    cca2: 'LV',
    cca3: 'LVA',
    ccn3: '428',
    id: 'LVA',
  },
  {
    code: 'LB',
    internationalDialingCode: '961',
    currencyCode: 'LBP',
    flag: 'https://restcountries.eu/data/lbn.svg',
    cioc: 'LIB',
    name: 'Lebanon',
    demonym: 'Lebanese',
    cca2: 'LB',
    cca3: 'LBN',
    ccn3: '422',
    id: 'LBN',
  },
  {
    code: 'LS',
    internationalDialingCode: '266',
    currencyCode: 'LSL',
    flag: 'https://restcountries.eu/data/lso.svg',
    cioc: 'LES',
    name: 'Lesotho',
    demonym: 'Mosotho',
    cca2: 'LS',
    cca3: 'LSO',
    ccn3: '426',
    id: 'LSO',
  },
  {
    code: 'LR',
    internationalDialingCode: '231',
    currencyCode: 'LRD',
    flag: 'https://restcountries.eu/data/lbr.svg',
    cioc: 'LBR',
    name: 'Liberia',
    demonym: 'Liberian',
    cca2: 'LR',
    cca3: 'LBR',
    ccn3: '430',
    id: 'LBR',
  },
  {
    code: 'LY',
    internationalDialingCode: '218',
    currencyCode: 'LYD',
    flag: 'https://restcountries.eu/data/lby.svg',
    cioc: 'LBA',
    name: 'Libya',
    demonym: 'Libyan',
    cca2: 'LY',
    cca3: 'LBY',
    ccn3: '434',
    id: 'LBY',
  },
  {
    code: 'LI',
    internationalDialingCode: '423',
    currencyCode: 'CHF',
    flag: 'https://restcountries.eu/data/lie.svg',
    cioc: 'LIE',
    name: 'Liechtenstein',
    demonym: 'Liechtensteiner',
    cca2: 'LI',
    cca3: 'LIE',
    ccn3: '438',
    id: 'LIE',
  },
  {
    code: 'LT',
    internationalDialingCode: '370',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/ltu.svg',
    cioc: 'LTU',
    name: 'Lithuania',
    demonym: 'Lithuanian',
    cca2: 'LT',
    cca3: 'LTU',
    ccn3: '440',
    id: 'LTU',
  },
  {
    code: 'LU',
    internationalDialingCode: '352',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/lux.svg',
    cioc: 'LUX',
    name: 'Luxembourg',
    demonym: 'Luxembourger',
    cca2: 'LU',
    cca3: 'LUX',
    ccn3: '442',
    id: 'LUX',
  },
  {
    code: 'MO',
    internationalDialingCode: '853',
    currencyCode: 'MOP',
    flag: 'https://restcountries.eu/data/mac.svg',
    cioc: 'MAC',
    name: 'Macao',
    demonym: 'Chinese',
    cca2: 'MO',
    cca3: 'MAC',
    ccn3: '446',
    id: 'MAC',
  },
  {
    code: 'MK',
    internationalDialingCode: '389',
    currencyCode: 'MKD',
    flag: 'https://restcountries.eu/data/mkd.svg',
    cioc: 'MKD',
    name: 'Macedonia',
    demonym: 'Macedonian',
    cca2: 'MK',
    cca3: 'MKD',
    ccn3: '807',
    id: 'MKD',
  },
  {
    code: 'MG',
    internationalDialingCode: '261',
    currencyCode: 'MGA',
    flag: 'https://restcountries.eu/data/mdg.svg',
    cioc: 'MAD',
    name: 'Madagascar',
    demonym: 'Malagasy',
    cca2: 'MG',
    cca3: 'MDG',
    ccn3: '450',
    id: 'MDG',
  },
  {
    code: 'MW',
    internationalDialingCode: '265',
    currencyCode: 'MWK',
    flag: 'https://restcountries.eu/data/mwi.svg',
    cioc: 'MAW',
    name: 'Malawi',
    demonym: 'Malawian',
    cca2: 'MW',
    cca3: 'MWI',
    ccn3: '454',
    id: 'MWI',
  },
  {
    code: 'MY',
    internationalDialingCode: '60',
    currencyCode: 'MYR',
    flag: 'https://restcountries.eu/data/mys.svg',
    cioc: 'MAS',
    name: 'Malaysia',
    demonym: 'Malaysian',
    cca2: 'MY',
    cca3: 'MYS',
    ccn3: '458',
    id: 'MYS',
  },
  {
    code: 'MV',
    internationalDialingCode: '960',
    currencyCode: 'MVR',
    flag: 'https://restcountries.eu/data/mdv.svg',
    cioc: 'MDV',
    name: 'Maldives',
    demonym: 'Maldivan',
    cca2: 'MV',
    cca3: 'MDV',
    ccn3: '462',
    id: 'MDV',
  },
  {
    code: 'ML',
    internationalDialingCode: '223',
    currencyCode: 'XOF',
    flag: 'https://restcountries.eu/data/mli.svg',
    cioc: 'MLI',
    name: 'Mali',
    demonym: 'Malian',
    cca2: 'ML',
    cca3: 'MLI',
    ccn3: '466',
    id: 'MLI',
  },
  {
    code: 'MT',
    internationalDialingCode: '356',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/mlt.svg',
    cioc: 'MLT',
    name: 'Malta',
    demonym: 'Maltese',
    cca2: 'MT',
    cca3: 'MLT',
    ccn3: '470',
    id: 'MLT',
  },
  {
    code: 'MH',
    internationalDialingCode: '692',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/mhl.svg',
    cioc: 'MHL',
    name: 'Marshall Islands',
    demonym: 'Marshallese',
    cca2: 'MH',
    cca3: 'MHL',
    ccn3: '584',
    id: 'MHL',
  },
  {
    code: 'MR',
    internationalDialingCode: '222',
    currencyCode: 'MRO',
    flag: 'https://restcountries.eu/data/mrt.svg',
    cioc: 'MTN',
    name: 'Mauritania',
    demonym: 'Mauritanian',
    cca2: 'MR',
    cca3: 'MRT',
    ccn3: '478',
    id: 'MRT',
  },
  {
    code: 'MU',
    internationalDialingCode: '230',
    currencyCode: 'MUR',
    flag: 'https://restcountries.eu/data/mus.svg',
    cioc: 'MRI',
    name: 'Mauritius',
    demonym: 'Mauritian',
    cca2: 'MU',
    cca3: 'MUS',
    ccn3: '480',
    id: 'MUS',
  },
  {
    code: 'YT',
    internationalDialingCode: '262',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/myt.svg',
    cioc: 'MYT',
    name: 'Mayotte',
    demonym: 'French',
    cca2: 'YT',
    cca3: 'MYT',
    ccn3: '175',
    id: 'MYT',
  },
  {
    code: 'MX',
    internationalDialingCode: '52',
    currencyCode: 'MXN',
    flag: 'https://restcountries.eu/data/mex.svg',
    cioc: 'MEX',
    name: 'Mexico',
    demonym: 'Mexican',
    cca2: 'MX',
    cca3: 'MEX',
    ccn3: '484',
    id: 'MEX',
  },
  {
    code: 'FM',
    internationalDialingCode: '691',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/fsm.svg',
    cioc: 'FSM',
    name: 'Micronesia',
    demonym: 'Micronesian',
    cca2: 'FM',
    cca3: 'FSM',
    ccn3: '583',
    id: 'FSM',
  },
  {
    code: 'MD',
    internationalDialingCode: '373',
    currencyCode: 'MDL',
    flag: 'https://restcountries.eu/data/mda.svg',
    cioc: 'MDA',
    name: 'Moldova (Republic of)',
    demonym: 'Moldovan',
    cca2: 'MD',
    cca3: 'MDA',
    ccn3: '498',
    id: 'MDA',
  },
  {
    code: 'MC',
    internationalDialingCode: '377',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/mco.svg',
    cioc: 'MON',
    name: 'Monaco',
    demonym: 'Monegasque',
    cca2: 'MC',
    cca3: 'MCO',
    ccn3: '492',
    id: 'MCO',
  },
  {
    code: 'MN',
    internationalDialingCode: '976',
    currencyCode: 'MNT',
    flag: 'https://restcountries.eu/data/mng.svg',
    cioc: 'MGL',
    name: 'Mongolia',
    demonym: 'Mongolian',
    cca2: 'MN',
    cca3: 'MNG',
    ccn3: '496',
    id: 'MNG',
  },
  {
    code: 'ME',
    internationalDialingCode: '382',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/mne.svg',
    cioc: 'MNE',
    name: 'Montenegro',
    demonym: 'Montenegrin',
    cca2: 'ME',
    cca3: 'MNE',
    ccn3: '499',
    id: 'MNE',
  },
  {
    code: 'MS',
    internationalDialingCode: '664',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/msr.svg',
    cioc: 'MSR',
    name: 'Montserrat',
    demonym: 'Montserratian',
    cca2: 'MS',
    cca3: 'MSR',
    ccn3: '500',
    id: 'MSR',
  },
  {
    code: 'MA',
    internationalDialingCode: '212',
    currencyCode: 'MAD',
    flag: 'https://restcountries.eu/data/mar.svg',
    cioc: 'MAR',
    name: 'Morocco',
    demonym: 'Moroccan',
    cca2: 'MA',
    cca3: 'MAR',
    ccn3: '504',
    id: 'MAR',
  },
  {
    code: 'MZ',
    internationalDialingCode: '258',
    currencyCode: 'MZN',
    flag: 'https://restcountries.eu/data/moz.svg',
    cioc: 'MOZ',
    name: 'Mozambique',
    demonym: 'Mozambican',
    cca2: 'MZ',
    cca3: 'MOZ',
    ccn3: '508',
    id: 'MOZ',
  },
  {
    code: 'MM',
    internationalDialingCode: '95',
    currencyCode: 'MMK',
    flag: 'https://restcountries.eu/data/mmr.svg',
    cioc: 'MYA',
    name: 'Myanmar',
    demonym: 'Burmese',
    cca2: 'MM',
    cca3: 'MMR',
    ccn3: '104',
    id: 'MMR',
  },
  {
    code: 'NA',
    internationalDialingCode: '264',
    currencyCode: 'NAD',
    flag: 'https://restcountries.eu/data/nam.svg',
    cioc: 'NAM',
    name: 'Namibia',
    demonym: 'Namibian',
    cca2: 'NA',
    cca3: 'NAM',
    ccn3: '516',
    id: 'NAM',
  },
  {
    code: 'NR',
    internationalDialingCode: '674',
    currencyCode: 'AUD',
    flag: 'https://restcountries.eu/data/nru.svg',
    cioc: 'NRU',
    name: 'Nauru',
    demonym: 'Nauruan',
    cca2: 'NR',
    cca3: 'NRU',
    ccn3: '520',
    id: 'NRU',
  },
  {
    code: 'NP',
    internationalDialingCode: '977',
    currencyCode: 'NPR',
    flag: 'https://restcountries.eu/data/npl.svg',
    cioc: 'NEP',
    name: 'Nepal',
    demonym: 'Nepalese',
    cca2: 'NP',
    cca3: 'NPL',
    ccn3: '524',
    id: 'NPL',
  },
  {
    code: 'NL',
    internationalDialingCode: '31',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/nld.svg',
    cioc: 'NED',
    name: 'Netherlands',
    demonym: 'Dutch',
    cca2: 'NL',
    cca3: 'NLD',
    ccn3: '528',
    id: 'NLD',
  },
  {
    code: 'NC',
    internationalDialingCode: '687',
    currencyCode: 'XPF',
    flag: 'https://restcountries.eu/data/ncl.svg',
    cioc: 'NCL',
    name: 'New Caledonia',
    demonym: 'New Caledonian',
    cca2: 'NC',
    cca3: 'NCL',
    ccn3: '540',
    id: 'NCL',
  },
  {
    code: 'NZ',
    internationalDialingCode: '64',
    currencyCode: 'NZD',
    flag: 'https://restcountries.eu/data/nzl.svg',
    cioc: 'NZL',
    name: 'New Zealand',
    demonym: 'New Zealander',
    cca2: 'NZ',
    cca3: 'NZL',
    ccn3: '554',
    id: 'NZL',
  },
  {
    code: 'NI',
    internationalDialingCode: '505',
    currencyCode: 'NIO',
    flag: 'https://restcountries.eu/data/nic.svg',
    cioc: 'NCA',
    name: 'Nicaragua',
    demonym: 'Nicaraguan',
    cca2: 'NI',
    cca3: 'NIC',
    ccn3: '558',
    id: 'NIC',
  },
  {
    code: 'NE',
    internationalDialingCode: '227',
    currencyCode: 'XOF',
    flag: 'https://restcountries.eu/data/ner.svg',
    cioc: 'NIG',
    name: 'Niger',
    demonym: 'Nigerien',
    cca2: 'NE',
    cca3: 'NER',
    ccn3: '562',
    id: 'NER',
  },
  {
    code: 'NG',
    internationalDialingCode: '234',
    currencyCode: 'NGN',
    flag: 'https://restcountries.eu/data/nga.svg',
    cioc: 'NGR',
    name: 'Nigeria',
    demonym: 'Nigerian',
    cca2: 'NG',
    cca3: 'NGA',
    ccn3: '566',
    id: 'NGA',
  },
  {
    code: 'NU',
    internationalDialingCode: '683',
    currencyCode: 'NZD',
    flag: 'https://restcountries.eu/data/niu.svg',
    cioc: 'NIU',
    name: 'Niue',
    demonym: 'Niuean',
    cca2: 'NU',
    cca3: 'NIU',
    ccn3: '570',
    id: 'NIU',
  },
  {
    code: 'KP',
    internationalDialingCode: '850',
    currencyCode: 'KPW',
    flag: 'https://restcountries.eu/data/prk.svg',
    cioc: 'PRK',
    name: 'North Korea',
    demonym: 'North Korean',
    cca2: 'KP',
    cca3: 'PRK',
    ccn3: '408',
    id: 'PRK',
  },
  {
    code: 'MP',
    internationalDialingCode: '670',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/mnp.svg',
    cioc: 'MNP',
    name: 'Northern Mariana Islands',
    demonym: 'American',
    cca2: 'MP',
    cca3: 'MNP',
    ccn3: '580',
    id: 'MNP',
  },
  {
    code: 'NO',
    internationalDialingCode: '47',
    currencyCode: 'NOK',
    flag: 'https://restcountries.eu/data/nor.svg',
    cioc: 'NOR',
    name: 'Norway',
    demonym: 'Norwegian',
    cca2: 'NO',
    cca3: 'NOR',
    ccn3: '578',
    id: 'NOR',
  },
  {
    code: 'OM',
    internationalDialingCode: '968',
    currencyCode: 'OMR',
    flag: 'https://restcountries.eu/data/omn.svg',
    cioc: 'OMA',
    name: 'Oman',
    demonym: 'Omani',
    cca2: 'OM',
    cca3: 'OMN',
    ccn3: '512',
    id: 'OMN',
  },
  {
    code: 'PK',
    internationalDialingCode: '92',
    currencyCode: 'PKR',
    flag: 'https://restcountries.eu/data/pak.svg',
    cioc: 'PAK',
    name: 'Pakistan',
    demonym: 'Pakistani',
    cca2: 'PK',
    cca3: 'PAK',
    ccn3: '586',
    id: 'PAK',
  },
  {
    code: 'PS',
    internationalDialingCode: '970',
    currencyCode: 'ILS',
    flag: 'https://restcountries.eu/data/pse.svg',
    cioc: 'PLE',
    name: 'Palestine, State of',
    demonym: 'Palestinian',
    cca2: 'PS',
    cca3: 'PSE',
    ccn3: '275',
    id: 'PSE',
  },
  {
    code: 'PA',
    internationalDialingCode: '507',
    currencyCode: 'PAB',
    flag: 'https://restcountries.eu/data/pan.svg',
    cioc: 'PAN',
    name: 'Panama',
    demonym: 'Panamanian',
    cca2: 'PA',
    cca3: 'PAN',
    ccn3: '591',
    id: 'PAN',
  },
  {
    code: 'PG',
    internationalDialingCode: '675',
    currencyCode: 'PGK',
    flag: 'https://restcountries.eu/data/png.svg',
    cioc: 'PNG',
    name: 'Papua New Guinea',
    demonym: 'Papua New Guinean',
    cca2: 'PG',
    cca3: 'PNG',
    ccn3: '598',
    id: 'PNG',
  },
  {
    code: 'PY',
    internationalDialingCode: '595',
    currencyCode: 'PYG',
    flag: 'https://restcountries.eu/data/pry.svg',
    cioc: 'PAR',
    name: 'Paraguay',
    demonym: 'Paraguayan',
    cca2: 'PY',
    cca3: 'PRY',
    ccn3: '600',
    id: 'PRY',
  },
  {
    code: 'PE',
    internationalDialingCode: '51',
    currencyCode: 'PEN',
    flag: 'https://restcountries.eu/data/per.svg',
    cioc: 'PER',
    name: 'Peru',
    demonym: 'Peruvian',
    cca2: 'PE',
    cca3: 'PER',
    ccn3: '604',
    id: 'PER',
  },
  {
    code: 'PH',
    internationalDialingCode: '63',
    currencyCode: 'PHP',
    flag: 'https://restcountries.eu/data/phl.svg',
    cioc: 'PHI',
    name: 'Philippines',
    demonym: 'Filipino',
    cca2: 'PH',
    cca3: 'PHL',
    ccn3: '608',
    id: 'PHL',
  },
  {
    code: 'PN',
    internationalDialingCode: '64',
    currencyCode: 'NZD',
    flag: 'https://restcountries.eu/data/pcn.svg',
    cioc: 'PCN',
    name: 'Pitcairn',
    demonym: 'Pitcairn Islander',
    cca2: 'PN',
    cca3: 'PCN',
    ccn3: '612',
    id: 'PCN',
  },
  {
    code: 'PL',
    internationalDialingCode: '48',
    currencyCode: 'PLN',
    flag: 'https://restcountries.eu/data/pol.svg',
    cioc: 'POL',
    name: 'Poland',
    demonym: 'Polish',
    cca2: 'PL',
    cca3: 'POL',
    ccn3: '616',
    id: 'POL',
  },
  {
    code: 'PT',
    internationalDialingCode: '351',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/prt.svg',
    cioc: 'POR',
    name: 'Portugal',
    demonym: 'Portuguese',
    cca2: 'PT',
    cca3: 'PRT',
    ccn3: '620',
    id: 'PRT',
  },
  {
    code: 'PR',
    internationalDialingCode: '787',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/pri.svg',
    cioc: 'PUR',
    name: 'Puerto Rico',
    demonym: 'Puerto Rican',
    cca2: 'PR',
    cca3: 'PRI',
    ccn3: '630',
    id: 'PRI',
  },
  {
    code: 'QA',
    internationalDialingCode: '974',
    currencyCode: 'QAR',
    flag: 'https://restcountries.eu/data/qat.svg',
    cioc: 'QAT',
    name: 'Qatar',
    demonym: 'Qatari',
    cca2: 'QA',
    cca3: 'QAT',
    ccn3: '634',
    id: 'QAT',
  },
  {
    code: 'RO',
    internationalDialingCode: '40',
    currencyCode: 'RON',
    flag: 'https://restcountries.eu/data/rou.svg',
    cioc: 'ROU',
    name: 'Romania',
    demonym: 'Romanian',
    cca2: 'RO',
    cca3: 'ROU',
    ccn3: '642',
    id: 'ROU',
  },
  {
    code: 'RU',
    internationalDialingCode: '7',
    currencyCode: 'RUB',
    flag: 'https://restcountries.eu/data/rus.svg',
    cioc: 'RUS',
    name: 'Russian Federation',
    demonym: 'Russian',
    cca2: 'RU',
    cca3: 'RUS',
    ccn3: '643',
    id: 'RUS',
  },
  {
    code: 'RW',
    internationalDialingCode: '250',
    currencyCode: 'RWF',
    flag: 'https://restcountries.eu/data/rwa.svg',
    cioc: 'RWA',
    name: 'Rwanda',
    demonym: 'Rwandan',
    cca2: 'RW',
    cca3: 'RWA',
    ccn3: '646',
    id: 'RWA',
  },
  {
    code: 'BL',
    internationalDialingCode: '590',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/blm.svg',
    cioc: 'BLM',
    name: 'Saint Barthelemy',
    demonym: 'Saint Barthelemy',
    cca2: 'BL',
    cca3: 'BLM',
    ccn3: '652',
    id: 'BLM',
  },
  {
    code: 'SH',
    internationalDialingCode: '290',
    currencyCode: 'SHP',
    flag: 'https://restcountries.eu/data/shn.svg',
    cioc: 'SHN',
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    demonym: 'Saint Helenian',
    cca2: 'SH',
    cca3: 'SHN',
    ccn3: '654',
    id: 'SHN',
  },
  {
    code: 'KN',
    internationalDialingCode: '869',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/kna.svg',
    cioc: 'SKN',
    name: 'Saint Kitts and Nevis',
    demonym: 'Kittian and Nevisian',
    cca2: 'KN',
    cca3: 'KNA',
    ccn3: '659',
    id: 'KNA',
  },
  {
    code: 'LC',
    internationalDialingCode: '758',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/lca.svg',
    cioc: 'LCA',
    name: 'Saint Lucia',
    demonym: 'Saint Lucian',
    cca2: 'LC',
    cca3: 'LCA',
    ccn3: '662',
    id: 'LCA',
  },
  {
    code: 'MF',
    internationalDialingCode: '590',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/maf.svg',
    cioc: 'MAF',
    name: 'Saint Martin',
    demonym: 'Saint Martin',
    cca2: 'MF',
    cca3: 'MAF',
    ccn3: '663',
    id: 'MAF',
  },
  {
    code: 'PM',
    internationalDialingCode: '508',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/spm.svg',
    cioc: 'SPM',
    name: 'Saint Pierre and Miquelon',
    demonym: 'French',
    cca2: 'PM',
    cca3: 'SPM',
    ccn3: '666',
    id: 'SPM',
  },
  {
    code: 'VC',
    internationalDialingCode: '784',
    currencyCode: 'XCD',
    flag: 'https://restcountries.eu/data/vct.svg',
    cioc: 'VIN',
    name: 'Saint Vincent and the Grenadines',
    demonym: 'Saint Vincentian',
    cca2: 'VC',
    cca3: 'VCT',
    ccn3: '670',
    id: 'VCT',
  },
  {
    code: 'WS',
    internationalDialingCode: '685',
    currencyCode: 'WST',
    flag: 'https://restcountries.eu/data/wsm.svg',
    cioc: 'SAM',
    name: 'Samoa',
    demonym: 'Samoan',
    cca2: 'WS',
    cca3: 'WSM',
    ccn3: '882',
    id: 'WSM',
  },
  {
    code: 'SM',
    internationalDialingCode: '378',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/smr.svg',
    cioc: 'SMR',
    name: 'San Marino',
    demonym: 'Sammarinese',
    cca2: 'SM',
    cca3: 'SMR',
    ccn3: '674',
    id: 'SMR',
  },
  {
    code: 'ST',
    internationalDialingCode: '239',
    currencyCode: 'STD',
    flag: 'https://restcountries.eu/data/stp.svg',
    cioc: 'STP',
    name: 'Sao Tome and Principe',
    demonym: 'Sao Tomean',
    cca2: 'ST',
    cca3: 'STP',
    ccn3: '678',
    id: 'STP',
  },
  {
    code: 'SA',
    internationalDialingCode: '966',
    currencyCode: 'SAR',
    flag: 'https://restcountries.eu/data/sau.svg',
    cioc: 'KSA',
    name: 'Saudi Arabia',
    demonym: 'Saudi Arabian',
    cca2: 'SA',
    cca3: 'SAU',
    ccn3: '682',
    id: 'SAU',
  },
  {
    code: 'SN',
    internationalDialingCode: '221',
    currencyCode: 'XOF',
    flag: 'https://restcountries.eu/data/sen.svg',
    cioc: 'SEN',
    name: 'Senegal',
    demonym: 'Senegalese',
    cca2: 'SN',
    cca3: 'SEN',
    ccn3: '686',
    id: 'SEN',
  },
  {
    code: 'RS',
    internationalDialingCode: '381',
    currencyCode: 'RSD',
    flag: 'https://restcountries.eu/data/srb.svg',
    cioc: 'SRB',
    name: 'Serbia',
    demonym: 'Serbian',
    cca2: 'RS',
    cca3: 'SRB',
    ccn3: '688',
    id: 'SRB',
  },
  {
    code: 'SC',
    internationalDialingCode: '248',
    currencyCode: 'SCR',
    flag: 'https://restcountries.eu/data/syc.svg',
    cioc: 'SEY',
    name: 'Seychelles',
    demonym: 'Seychellois',
    cca2: 'SC',
    cca3: 'SYC',
    ccn3: '690',
    id: 'SYC',
  },
  {
    code: 'SL',
    internationalDialingCode: '232',
    currencyCode: 'SLL',
    flag: 'https://restcountries.eu/data/sle.svg',
    cioc: 'SLE',
    name: 'Sierra Leone',
    demonym: 'Sierra Leonean',
    cca2: 'SL',
    cca3: 'SLE',
    ccn3: '694',
    id: 'SLE',
  },
  {
    code: 'SG',
    internationalDialingCode: '65',
    currencyCode: 'SGD',
    flag: 'https://restcountries.eu/data/sgp.svg',
    cioc: 'SIN',
    name: 'Singapore',
    demonym: 'Singaporean',
    cca2: 'SG',
    cca3: 'SGP',
    ccn3: '702',
    id: 'SGP',
  },
  {
    code: 'SX',
    internationalDialingCode: '721',
    currencyCode: 'ANG',
    flag: 'https://restcountries.eu/data/sxm.svg',
    cioc: 'SXM',
    name: 'Sint Maarten (Dutch part)',
    demonym: 'Dutch',
    cca2: 'SX',
    cca3: 'SXM',
    ccn3: '534',
    id: 'SXM',
  },
  {
    code: 'SK',
    internationalDialingCode: '421',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/svk.svg',
    cioc: 'SVK',
    name: 'Slovakia',
    demonym: 'Slovak',
    cca2: 'SK',
    cca3: 'SVK',
    ccn3: '703',
    id: 'SVK',
  },
  {
    code: 'SI',
    internationalDialingCode: '386',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/svn.svg',
    cioc: 'SLO',
    name: 'Slovenia',
    demonym: 'Slovene',
    cca2: 'SI',
    cca3: 'SVN',
    ccn3: '705',
    id: 'SVN',
  },
  {
    code: 'SB',
    internationalDialingCode: '677',
    currencyCode: 'SBD',
    flag: 'https://restcountries.eu/data/slb.svg',
    cioc: 'SOL',
    name: 'Solomon Islands',
    demonym: 'Solomon Islander',
    cca2: 'SB',
    cca3: 'SLB',
    ccn3: '090',
    id: 'SLB',
  },
  {
    code: 'SO',
    internationalDialingCode: '252',
    currencyCode: 'SOS',
    flag: 'https://restcountries.eu/data/som.svg',
    cioc: 'SOM',
    name: 'Somalia',
    demonym: 'Somali',
    cca2: 'SO',
    cca3: 'SOM',
    ccn3: '706',
    id: 'SOM',
  },
  {
    code: 'ZA',
    internationalDialingCode: '27',
    currencyCode: 'ZAR',
    flag: 'https://restcountries.eu/data/zaf.svg',
    cioc: 'RSA',
    name: 'South Africa',
    demonym: 'South Africa',
    cca2: 'ZA',
    cca3: 'ZAF',
    ccn3: '710',
    id: 'ZAF',
  },
  {
    code: 'SS',
    internationalDialingCode: '211',
    currencyCode: 'SSP',
    flag: 'https://restcountries.eu/data/ssd.svg',
    cioc: 'SSD',
    name: 'South Sudan',
    demonym: 'South Sudanese',
    cca2: 'SS',
    cca3: 'SSD',
    ccn3: '728',
    id: 'SSD',
  },
  {
    code: 'ES',
    internationalDialingCode: '34',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/esp.svg',
    cioc: 'ESP',
    name: 'Spain',
    demonym: 'Spanish',
    cca2: 'ES',
    cca3: 'ESP',
    ccn3: '724',
    id: 'ESP',
  },
  {
    code: 'LK',
    internationalDialingCode: '94',
    currencyCode: 'LKR',
    flag: 'https://restcountries.eu/data/lka.svg',
    cioc: 'SRI',
    name: 'Sri Lanka',
    demonym: 'Sri Lankan',
    cca2: 'LK',
    cca3: 'LKA',
    ccn3: '144',
    id: 'LKA',
  },
  {
    code: 'SD',
    internationalDialingCode: '249',
    currencyCode: 'SDG',
    flag: 'https://restcountries.eu/data/sdn.svg',
    cioc: 'SUD',
    name: 'Sudan',
    demonym: 'Sudanese',
    cca2: 'SD',
    cca3: 'SDN',
    ccn3: '729',
    id: 'SDN',
  },
  {
    code: 'SR',
    internationalDialingCode: '597',
    currencyCode: 'SRD',
    flag: 'https://restcountries.eu/data/sur.svg',
    cioc: 'SUR',
    name: 'Suriname',
    demonym: 'Surinamer',
    cca2: 'SR',
    cca3: 'SUR',
    ccn3: '740',
    id: 'SUR',
  },
  {
    code: 'SJ',
    internationalDialingCode: '47',
    currencyCode: 'NOK',
    flag: 'https://restcountries.eu/data/sjm.svg',
    cioc: 'SJM',
    name: 'Svalbard and Jan Mayen',
    demonym: 'Norwegian',
    cca2: 'SJ',
    cca3: 'SJM',
    ccn3: '744',
    id: 'SJM',
  },
  {
    code: 'SZ',
    internationalDialingCode: '268',
    currencyCode: 'SZL',
    flag: 'https://restcountries.eu/data/swz.svg',
    cioc: 'SWZ',
    name: 'Swaziland',
    demonym: 'Swazi',
    cca2: 'SZ',
    cca3: 'SWZ',
    ccn3: '748',
    id: 'SWZ',
  },
  {
    code: 'SE',
    internationalDialingCode: '46',
    currencyCode: 'SEK',
    flag: 'https://restcountries.eu/data/swe.svg',
    cioc: 'SWE',
    name: 'Sweden',
    demonym: 'Swedish',
    cca2: 'SE',
    cca3: 'SWE',
    ccn3: '752',
    id: 'SWE',
  },
  {
    code: 'CH',
    internationalDialingCode: '41',
    currencyCode: 'CHF',
    flag: 'https://restcountries.eu/data/che.svg',
    cioc: 'SUI',
    name: 'Switzerland',
    demonym: 'Swiss',
    cca2: 'CH',
    cca3: 'CHE',
    ccn3: '756',
    id: 'CHE',
  },
  {
    code: 'SY',
    internationalDialingCode: '963',
    currencyCode: 'SYP',
    flag: 'https://restcountries.eu/data/syr.svg',
    cioc: 'SYR',
    name: 'Syrian Arab Republic',
    demonym: 'Syrian',
    cca2: 'SY',
    cca3: 'SYR',
    ccn3: '760',
    id: 'SYR',
  },
  {
    code: 'TW',
    internationalDialingCode: '886',
    currencyCode: 'TWD',
    flag: 'https://restcountries.eu/data/twn.svg',
    cioc: 'TPE',
    name: 'Taiwan',
    demonym: 'Taiwanese',
    cca2: 'TW',
    cca3: 'TWN',
    ccn3: '158',
    id: 'TWN',
  },
  {
    code: 'TJ',
    internationalDialingCode: '992',
    currencyCode: 'TJS',
    flag: 'https://restcountries.eu/data/tjk.svg',
    cioc: 'TJK',
    name: 'Tajikistan',
    demonym: 'Tadzhik',
    cca2: 'TJ',
    cca3: 'TJK',
    ccn3: '762',
    id: 'TJK',
  },
  {
    code: 'TZ',
    internationalDialingCode: '255',
    currencyCode: 'TZS',
    flag: 'https://restcountries.eu/data/tza.svg',
    cioc: 'TAN',
    name: 'Tanzania, United Republic of',
    demonym: 'Tanzanian',
    cca2: 'TZ',
    cca3: 'TZA',
    ccn3: '834',
    id: 'TZA',
  },
  {
    code: 'TH',
    internationalDialingCode: '66',
    currencyCode: 'THB',
    flag: 'https://restcountries.eu/data/tha.svg',
    cioc: 'THA',
    name: 'Thailand',
    demonym: 'Thai',
    cca2: 'TH',
    cca3: 'THA',
    ccn3: '764',
    id: 'THA',
  },
  {
    code: 'TL',
    internationalDialingCode: '670',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/tls.svg',
    cioc: 'TLS',
    name: 'Timor-Leste',
    demonym: 'East Timorese',
    cca2: 'TL',
    cca3: 'TLS',
    ccn3: '626',
    id: 'TLS',
  },
  {
    code: 'TG',
    internationalDialingCode: '228',
    currencyCode: 'XOF',
    flag: 'https://restcountries.eu/data/tgo.svg',
    cioc: 'TOG',
    name: 'Togo',
    demonym: 'Togolese',
    cca2: 'TG',
    cca3: 'TGO',
    ccn3: '768',
    id: 'TGO',
  },
  {
    code: 'TK',
    internationalDialingCode: '690',
    currencyCode: 'NZD',
    flag: 'https://restcountries.eu/data/tkl.svg',
    cioc: 'TKL',
    name: 'Tokelau',
    demonym: 'Tokelauan',
    cca2: 'TK',
    cca3: 'TKL',
    ccn3: '772',
    id: 'TKL',
  },
  {
    code: 'TO',
    internationalDialingCode: '676',
    currencyCode: 'TOP',
    flag: 'https://restcountries.eu/data/ton.svg',
    cioc: 'TGA',
    name: 'Tonga',
    demonym: 'Tongan',
    cca2: 'TO',
    cca3: 'TON',
    ccn3: '776',
    id: 'TON',
  },
  {
    code: 'TT',
    internationalDialingCode: '868',
    currencyCode: 'TTD',
    flag: 'https://restcountries.eu/data/tto.svg',
    cioc: 'TTO',
    name: 'Trinidad and Tobago',
    demonym: 'Trinidadian',
    cca2: 'TT',
    cca3: 'TTO',
    ccn3: '780',
    id: 'TTO',
  },
  {
    code: 'TN',
    internationalDialingCode: '216',
    currencyCode: 'TND',
    flag: 'https://restcountries.eu/data/tun.svg',
    cioc: 'TUN',
    name: 'Tunisia',
    demonym: 'Tunisian',
    cca2: 'TN',
    cca3: 'TUN',
    ccn3: '788',
    id: 'TUN',
  },
  {
    code: 'TR',
    internationalDialingCode: '90',
    currencyCode: 'TRY',
    flag: 'https://restcountries.eu/data/tur.svg',
    cioc: 'TUR',
    name: 'Turkey',
    demonym: 'Turkish',
    cca2: 'TR',
    cca3: 'TUR',
    ccn3: '792',
    id: 'TUR',
  },
  {
    code: 'TM',
    internationalDialingCode: '993',
    currencyCode: 'TMT',
    flag: 'https://restcountries.eu/data/tkm.svg',
    cioc: 'TKM',
    name: 'Turkmenistan',
    demonym: 'Turkmen',
    cca2: 'TM',
    cca3: 'TKM',
    ccn3: '795',
    id: 'TKM',
  },
  {
    code: 'TC',
    internationalDialingCode: '649',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/tca.svg',
    cioc: 'TCA',
    name: 'Turks and Caicos Islands',
    demonym: 'Turks and Caicos',
    cca2: 'TC',
    cca3: 'TCA',
    ccn3: '796',
    id: 'TCA',
  },
  {
    code: 'TV',
    internationalDialingCode: '688',
    currencyCode: 'AUD',
    flag: 'https://restcountries.eu/data/tuv.svg',
    cioc: 'TUV',
    name: 'Tuvalu',
    demonym: 'Tuvaluan',
    cca2: 'TV',
    cca3: 'TUV',
    ccn3: '798',
    id: 'TUV',
  },
  {
    code: 'UG',
    internationalDialingCode: '256',
    currencyCode: 'UGX',
    flag: 'https://restcountries.eu/data/uga.svg',
    cioc: 'UGA',
    name: 'Uganda',
    demonym: 'Ugandan',
    cca2: 'UG',
    cca3: 'UGA',
    ccn3: '800',
    id: 'UGA',
  },
  {
    code: 'UA',
    internationalDialingCode: '380',
    currencyCode: 'UAH',
    flag: 'https://restcountries.eu/data/ukr.svg',
    cioc: 'UKR',
    name: 'Ukraine',
    demonym: 'Ukrainian',
    cca2: 'UA',
    cca3: 'UKR',
    ccn3: '804',
    id: 'UKR',
  },
  {
    code: 'AE',
    internationalDialingCode: '971',
    currencyCode: 'AED',
    flag: 'https://restcountries.eu/data/are.svg',
    cioc: 'UAE',
    name: 'United Arab Emirates',
    demonym: 'Emirati',
    cca2: 'AE',
    cca3: 'ARE',
    ccn3: '784',
    id: 'ARE',
  },
  {
    code: 'UY',
    internationalDialingCode: '598',
    currencyCode: 'UYU',
    flag: 'https://restcountries.eu/data/ury.svg',
    cioc: 'URU',
    name: 'Uruguay',
    demonym: 'Uruguayan',
    cca2: 'UY',
    cca3: 'URY',
    ccn3: '858',
    id: 'URY',
  },
  {
    code: 'UZ',
    internationalDialingCode: '998',
    currencyCode: 'UZS',
    flag: 'https://restcountries.eu/data/uzb.svg',
    cioc: 'UZB',
    name: 'Uzbekistan',
    demonym: 'Uzbekistani',
    cca2: 'UZ',
    cca3: 'UZB',
    ccn3: '860',
    id: 'UZB',
  },
  {
    code: 'VU',
    internationalDialingCode: '678',
    currencyCode: 'VUV',
    flag: 'https://restcountries.eu/data/vut.svg',
    cioc: 'VAN',
    name: 'Vanuatu',
    demonym: 'Ni-Vanuatu',
    cca2: 'VU',
    cca3: 'VUT',
    ccn3: '548',
    id: 'VUT',
  },
  {
    code: 'VE',
    internationalDialingCode: '58',
    currencyCode: 'VEF',
    flag: 'https://restcountries.eu/data/ven.svg',
    cioc: 'VEN',
    name: 'Venezuela',
    demonym: 'Venezuelan',
    cca2: 'VE',
    cca3: 'VEN',
    ccn3: '862',
    id: 'VEN',
  },
  {
    code: 'VN',
    internationalDialingCode: '84',
    currencyCode: 'VND',
    flag: 'https://restcountries.eu/data/vnm.svg',
    cioc: 'VIE',
    name: 'Viet Nam',
    demonym: 'Vietnamese',
    cca2: 'VN',
    cca3: 'VNM',
    ccn3: '704',
    id: 'VNM',
  },
  {
    code: 'VG',
    internationalDialingCode: '284',
    currencyCode: 'EUR',
    flag: 'https://restcountries.eu/data/vgb.svg',
    cioc: 'IVB',
    name: 'Virgin Islands (British)',
    demonym: 'Virgin Islander',
    cca2: 'VG',
    cca3: 'VGB',
    ccn3: '092',
    id: 'VGB',
  },
  {
    code: 'VI',
    internationalDialingCode: '340',
    currencyCode: 'USD',
    flag: 'https://restcountries.eu/data/vir.svg',
    cioc: 'ISV',
    name: 'Virgin Islands (U.S.)',
    demonym: 'Virgin Islander',
    cca2: 'VI',
    cca3: 'VIR',
    ccn3: '850',
    id: 'VIR',
  },
  {
    code: 'WF',
    internationalDialingCode: '681',
    currencyCode: 'XPF',
    flag: 'https://restcountries.eu/data/wlf.svg',
    cioc: 'WLF',
    name: 'Wallis and Futuna',
    demonym: 'Wallis and Futuna',
    cca2: 'WF',
    cca3: 'WLF',
    ccn3: '876',
    id: 'WLF',
  },
  {
    code: 'EH',
    internationalDialingCode: '212',
    currencyCode: 'MAD',
    flag: 'https://restcountries.eu/data/esh.svg',
    cioc: 'ESH',
    name: 'Western Sahara',
    demonym: 'Sahrawi',
    cca2: 'EH',
    cca3: 'ESH',
    ccn3: '732',
    id: 'ESH',
  },
  {
    code: 'YE',
    internationalDialingCode: '967',
    currencyCode: 'YER',
    flag: 'https://restcountries.eu/data/yem.svg',
    cioc: 'YEM',
    name: 'Yemen',
    demonym: 'Yemeni',
    cca2: 'YE',
    cca3: 'YEM',
    ccn3: '887',
    id: 'YEM',
  },
  {
    code: 'ZM',
    internationalDialingCode: '260',
    currencyCode: 'ZMW',
    flag: 'https://restcountries.eu/data/zmb.svg',
    cioc: 'ZAM',
    name: 'Zambia',
    demonym: 'Zambian',
    cca2: 'ZM',
    cca3: 'ZMB',
    ccn3: '894',
    id: 'ZMB',
  },
  {
    code: 'ZW',
    internationalDialingCode: '263',
    currencyCode: 'BWP',
    flag: 'https://restcountries.eu/data/zwe.svg',
    cioc: 'ZIM',
    name: 'Zimbabwe',
    demonym: 'Zimbabwean',
    cca2: 'ZW',
    cca3: 'ZWE',
    ccn3: '716',
    id: 'ZWE',
  },
];
